name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.10", "3.11"]
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
      - name: Upgrade pip
        run: python -m pip install --upgrade pip
      - name: Install minimal CPU deps
        run: |
          pip install --no-cache-dir torch --index-url https://download.pytorch.org/whl/cpu
          pip install --no-cache-dir pytest
      - name: Install project (no extras)
        run: pip install -e . --no-deps
      - name: Run tests
        run: pytest -q
